# Allow bitstream generation while HDMI port/source-set alignment is being sorted out.
# These DRC severity overrides are intentional.
set_property SEVERITY Warning [get_drc_checks UCIO-1]
set_property SEVERITY Warning [get_drc_checks NSTD-1]

#**************************************************************
# USB timing
#**************************************************************
create_clock -period 16.500 -name ulpi_clock [get_ports ULPI_CLOCK]

# Model ~0.5 ns delay from PHY → FPGA (resistor, trace)
set_clock_latency -source -late 0.500 [get_ports ULPI_CLOCK]

# Set Input Delay
set_input_delay -clock [get_clocks ulpi_clock] -max -add_delay 3.500 [get_ports {ULPI_DATA* ULPI_DIR ULPI_NXT}]
set_input_delay -clock [get_clocks ulpi_clock] -min -add_delay 1.500 [get_ports {ULPI_DATA* ULPI_DIR ULPI_NXT}]

# Set Output Delay
# max output delay (measured from next clock edge) = set_up of other device.
set_output_delay -clock [get_clocks ulpi_clock] -max -add_delay 3.000 [get_ports {ULPI_DATA* ULPI_STP}]
set_output_delay -clock [get_clocks ulpi_clock] -min -add_delay 0.000 [get_ports {ULPI_DATA* ULPI_STP}]

#**************************************************************
# RMII timing
#**************************************************************
create_clock -name {rmii_clock} -period 20 [get_ports RMII_REFCLK]
set_input_jitter [get_clocks -of_objects [get_ports RMII_REFCLK]] 0.900

# HDMI GT reference clock returned by the external clock synthesizer.
# HDMI_CLK_SYNTH is driven at 27 MHz; the expected return clock is 270 MHz.
create_clock -name hdmi_gt_refclk -period 3.703704 [get_ports HDMI_REFCLK_P]

# Set Input Delay (= clock to out from other device)
set_input_delay -clock [get_clocks -of_objects [get_ports RMII_REFCLK]] -max -add_delay 13.000 [get_ports {RMII_RX* RMII_CRS*}]
set_input_delay -clock [get_clocks -of_objects [get_ports RMII_REFCLK]] -min -add_delay 7.000 [get_ports {RMII_RX* RMII_CRS*}]

# Set Output Delay
# max output delay (measured from next clock edge) = set_up of other device.
set_output_delay -clock [get_clocks -of_objects [get_ports RMII_REFCLK]] -max -add_delay 4.000 [get_ports RMII_TX*]
set_output_delay -clock [get_clocks -of_objects [get_ports RMII_REFCLK]] -min -add_delay -2.000 [get_ports RMII_TX*]

#**************************************************************
# C64 System Clock (NTSC is the highest freq, 4x 8.1818 MHz)
#**************************************************************
create_clock -period 30.500 -name c64_ref_clock_from_ext_pll [get_ports CLOCK_C64_REF]
set_input_jitter [get_clocks -of_objects [get_ports CLOCK_C64_REF]] 0.900

#**************************************************************
# Synchronizers and other stuff.
#**************************************************************
# Put your own design elements and false paths here

#**************************************************************
# Mutually exclusive clocks
#**************************************************************
# Put your own mutually exclusive clocks here.

#**************************************************************
# Configuration
#**************************************************************
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CONFIG_MODE SPIx1 [current_design]
set_property INTERNAL_VREF 0.9 [get_iobanks 35]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]

# Memory
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports SDRAM_DQS*]
set_property IOSTANDARD HSTL_II_18 [get_ports {SDRAM_DQ[*]}]
set_property IOSTANDARD HSTL_II_18 [get_ports SDRAM_DM*]
set_property IOSTANDARD HSTL_I_18 [get_ports SDRAM_CL*]
set_property IOSTANDARD HSTL_I_18 [get_ports SDRAM_A*]
set_property IOSTANDARD HSTL_I_18 [get_ports SDRAM_BA*]
set_property IOSTANDARD HSTL_I_18 [get_ports SDRAM_RASn]
set_property IOSTANDARD HSTL_I_18 [get_ports SDRAM_CASn]
set_property IOSTANDARD HSTL_I_18 [get_ports SDRAM_WEn]
set_property IOSTANDARD HSTL_I_18 [get_ports SDRAM_CSn]
set_property IOSTANDARD HSTL_I_18 [get_ports SDRAM_CKE]
set_property IOSTANDARD HSTL_I_18 [get_ports SDRAM_ODT]

# Mixed groups
set_property IOSTANDARD LVCMOS18 [get_ports AUDIO_BCLK]
set_property IOSTANDARD LVCMOS18 [get_ports AUDIO_LRCLK]
set_property IOSTANDARD LVCMOS18 [get_ports AUDIO_MCLK]
set_property IOSTANDARD LVCMOS18 [get_ports AUDIO_SDI]
set_property IOSTANDARD LVCMOS18 [get_ports AUDIO_SDO]
set_property IOSTANDARD LVCMOS33 [get_ports AUDIO_SPDIF]
set_property IOSTANDARD LVCMOS33 [get_ports ETH_LED_YELn]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_ADDR[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_ADDR[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_ADDR[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SLOT_ADDR[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports SLOT_RST_O]
set_property IOSTANDARD LVCMOS33 [get_ports SLOT_RST_I]
set_property IOSTANDARD LVCMOS33 [get_ports SLOT_RWn]
set_property IOSTANDARD LVCMOS33 [get_ports SLOT_SID1n]
set_property IOSTANDARD LVCMOS33 [get_ports SLOT_SID2n]
set_property IOSTANDARD LVCMOS33 [get_ports SLOT_SID_ADDR]
set_property IOSTANDARD LVCMOS33 [get_ports SLOT_IRQn]
set_property IOSTANDARD LVCMOS33 [get_ports SLOT_NMIn]
set_property IOSTANDARD LVCMOS33 [get_ports SLOT_PWR]
set_property IOSTANDARD LVCMOS18 [get_ports SLOT_ADDRDIR]
set_property IOSTANDARD LVCMOS18 [get_ports SLOT_ADDROEn]
set_property IOSTANDARD LVCMOS18 [get_ports SLOT_DATADIR]
set_property IOSTANDARD LVCMOS18 [get_ports SLOT_DATAOEn]
set_property IOSTANDARD LVCMOS18 [get_ports SLOT_BA]
set_property IOSTANDARD LVCMOS33 [get_ports SLOT_DMAn]
set_property IOSTANDARD LVCMOS18 [get_ports SLOT_DOTCLK]
set_property IOSTANDARD LVCMOS33 [get_ports SLOT_EXROMn]
set_property IOSTANDARD LVCMOS33 [get_ports SLOT_GAMEn]
set_property IOSTANDARD LVCMOS18 [get_ports SLOT_IO1n]
set_property IOSTANDARD LVCMOS18 [get_ports SLOT_IO2n]
set_property IOSTANDARD LVCMOS18 [get_ports SLOT_PHI2]
set_property IOSTANDARD LVCMOS18 [get_ports SLOT_ROMHn]
set_property IOSTANDARD LVCMOS18 [get_ports SLOT_ROMLn]
set_property IOSTANDARD LVCMOS18 [get_ports {SLOT_ADDR[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SLOT_ADDR[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SLOT_ADDR[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SLOT_ADDR[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SLOT_ADDR[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SLOT_ADDR[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SLOT_ADDR[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SLOT_ADDR[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SLOT_ADDR[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SLOT_ADDR[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SLOT_ADDR[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SLOT_ADDR[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SLOT_DATA[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SLOT_DATA[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SLOT_DATA[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SLOT_DATA[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SLOT_DATA[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SLOT_DATA[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SLOT_DATA[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SLOT_DATA[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports HDMI_DDC_EN]
set_property IOSTANDARD LVCMOS33 [get_ports HDMI_HPD]
set_property IOSTANDARD LVCMOS33 [get_ports HDMI_SCL]
set_property IOSTANDARD LVCMOS33 [get_ports HDMI_SDA]
set_property IOSTANDARD LVCMOS18 [get_ports HDMI_CLK_SYNTH]

set_property IOSTANDARD LVCMOS33 [get_ports KBJOY_RESTORE]
set_property IOSTANDARD LVCMOS18 [get_ports KBJOY_INT]

# Homogenous groups
set_property IOSTANDARD LVCMOS33 [get_ports HUB_*]
set_property IOSTANDARD LVCMOS33 [get_ports C2N_*]
set_property IOSTANDARD LVCMOS33 [get_ports IEC_*]
set_property IOSTANDARD LVCMOS33 [get_ports LED_*]
set_property IOSTANDARD LVCMOS33 [get_ports CIA_*]
set_property IOSTANDARD LVCMOS33 [get_ports KBJOY_1*]
set_property IOSTANDARD LVCMOS33 [get_ports KBJOY_2*]
set_property IOSTANDARD LVCMOS33 [get_ports FLASH_*]
set_property IOSTANDARD LVCMOS33 [get_ports UART_*]
set_property IOSTANDARD LVCMOS33 [get_ports BLING_*]
set_property IOSTANDARD LVCMOS33 [get_ports WIFI_*]
set_property IOSTANDARD LVCMOS33 [get_ports SD_*]
set_property IOSTANDARD LVCMOS33 [get_ports I2C33_*]

set_property DRIVE 4 [get_ports KBJOY_1*]
set_property DRIVE 4 [get_ports KBJOY_2*]
set_property DRIVE 4 [get_ports {ULPI_DATA[7]}]
set_property DRIVE 4 [get_ports {ULPI_DATA[6]}]
set_property DRIVE 4 [get_ports {ULPI_DATA[5]}]
set_property DRIVE 4 [get_ports {ULPI_DATA[4]}]
set_property DRIVE 4 [get_ports {ULPI_DATA[3]}]
set_property DRIVE 4 [get_ports {ULPI_DATA[2]}]
set_property DRIVE 4 [get_ports {ULPI_DATA[1]}]
set_property DRIVE 4 [get_ports {ULPI_DATA[0]}]
set_property DRIVE 4 [get_ports ULPI_REFCLK]
set_property DRIVE 4 [get_ports ULPI_RESET]
set_property DRIVE 4 [get_ports ULPI_STP]
set_property DRIVE 4 [get_ports SLOT_DATA*]
set_property DRIVE 4 [get_ports AVID*]
set_property DRIVE 4 [get_ports AUDIO_BCLK]
set_property DRIVE 4 [get_ports AUDIO_LRCLK]
set_property DRIVE 4 [get_ports AUDIO_MCLK]
set_property DRIVE 4 [get_ports AUDIO_SDI]
set_property DRIVE 4 [get_ports AUDIO_SPDIF]
set_property DRIVE 4 [get_ports {SLOT_ADDR[0]}]
set_property DRIVE 4 [get_ports {SLOT_ADDR[1]}]
set_property DRIVE 4 [get_ports {SLOT_ADDR[2]}]
set_property DRIVE 4 [get_ports {SLOT_ADDR[3]}]
set_property DRIVE 4 [get_ports {SLOT_ADDR[4]}]
set_property DRIVE 4 [get_ports {SLOT_ADDR[5]}]
set_property DRIVE 4 [get_ports {SLOT_ADDR[6]}]
set_property DRIVE 4 [get_ports {SLOT_ADDR[7]}]
set_property DRIVE 4 [get_ports {SLOT_ADDR[8]}]
set_property DRIVE 4 [get_ports {SLOT_ADDR[9]}]
set_property DRIVE 4 [get_ports {SLOT_ADDR[10]}]
set_property DRIVE 4 [get_ports {SLOT_ADDR[11]}]
#set_property DRIVE 4 [get_ports {SLOT_ADDR[12]}]
#set_property DRIVE 4 [get_ports {SLOT_ADDR[13]}]
#set_property DRIVE 4 [get_ports {SLOT_ADDR[14]}]
#set_property DRIVE 4 [get_ports {SLOT_ADDR[15]}]
set_property DRIVE 4 [get_ports SLOT_ADDRDIR]
set_property DRIVE 4 [get_ports SLOT_ADDROEn]
set_property DRIVE 4 [get_ports SLOT_PHI2]
set_property DRIVE 4 [get_ports SLOT_ROMHn]
set_property DRIVE 4 [get_ports SLOT_DOTCLK]
set_property DRIVE 4 [get_ports SLOT_IO1n]
set_property DRIVE 4 [get_ports SLOT_IO2n]
set_property DRIVE 4 [get_ports SLOT_BA]
set_property DRIVE 4 [get_ports SLOT_ROMLn]
set_property DRIVE 4 [get_ports SLOT_RST_O]
set_property DRIVE 4 [get_ports SLOT_SID_ADDR]
set_property DRIVE 4 [get_ports SLOT_SID1n]
set_property DRIVE 4 [get_ports SLOT_SID2n]
set_property DRIVE 4 [get_ports HDMI_CLK_SYNTH]

set_property IOSTANDARD LVCMOS18 [get_ports AVID_*]
set_property IOSTANDARD LVCMOS33 [get_ports UI_*]
set_property IOSTANDARD LVCMOS18 [get_ports RMII_*]
set_property IOSTANDARD LVCMOS18 [get_ports MDIO_*]
set_property IOSTANDARD LVCMOS18 [get_ports ULPI_*]
set_property IOSTANDARD LVCMOS18 [get_ports I2C18_*]
set_property IOSTANDARD LVCMOS18 [get_ports BOARD_REV*]
set_property IOSTANDARD LVCMOS18 [get_ports CLOCK_*]
set_property IOSTANDARD LVCMOS18 [get_ports PADDLE_CMP*]

set_property IOSTANDARD LVCMOS18 [get_ports SPEAKER_DATA]
set_property IOSTANDARD LVCMOS33 [get_ports PADDLE_DIS]
set_property IOSTANDARD LVCMOS33 [get_ports PADDLE_ADJ]

set_property PACKAGE_PIN F4 [get_ports {SDRAM_A[13]}]
set_property PACKAGE_PIN B1 [get_ports {SDRAM_A[12]}]
set_property PACKAGE_PIN A1 [get_ports {SDRAM_A[11]}]
set_property PACKAGE_PIN C2 [get_ports {SDRAM_A[10]}]
set_property PACKAGE_PIN B2 [get_ports {SDRAM_A[9]}]
set_property PACKAGE_PIN E1 [get_ports SDRAM_CLK]
set_property PACKAGE_PIN D1 [get_ports SDRAM_CLKn]
set_property PACKAGE_PIN E2 [get_ports {SDRAM_A[8]}]
set_property PACKAGE_PIN D2 [get_ports {SDRAM_A[7]}]
set_property PACKAGE_PIN G1 [get_ports {SDRAM_A[6]}]
set_property PACKAGE_PIN F1 [get_ports {SDRAM_A[5]}]
set_property PACKAGE_PIN F3 [get_ports {SDRAM_A[4]}]
set_property PACKAGE_PIN E3 [get_ports {SDRAM_A[3]}]
set_property PACKAGE_PIN K1 [get_ports {SDRAM_A[2]}]
set_property PACKAGE_PIN J1 [get_ports {SDRAM_A[1]}]
set_property PACKAGE_PIN H2 [get_ports {SDRAM_A[0]}]
set_property PACKAGE_PIN G2 [get_ports {SDRAM_BA[2]}]
set_property PACKAGE_PIN K2 [get_ports {SDRAM_BA[1]}]
set_property PACKAGE_PIN J2 [get_ports {SDRAM_BA[0]}]
set_property PACKAGE_PIN J5 [get_ports SDRAM_RASn]
set_property PACKAGE_PIN H5 [get_ports SDRAM_CASn]
set_property PACKAGE_PIN H3 [get_ports SDRAM_WEn]
set_property PACKAGE_PIN G3 [get_ports SDRAM_CSn]
set_property PACKAGE_PIN H4 [get_ports SDRAM_CKE]
set_property PACKAGE_PIN G4 [get_ports SDRAM_ODT]
set_property PACKAGE_PIN K4 [get_ports {SDRAM_DQ[8]}]
set_property PACKAGE_PIN J4 [get_ports {SDRAM_DQ[9]}]
set_property PACKAGE_PIN L3 [get_ports {SDRAM_DQ[10]}]
set_property PACKAGE_PIN K3 [get_ports {SDRAM_DQ[11]}]
set_property PACKAGE_PIN M1 [get_ports {SDRAM_DQS[1]}]
set_property PACKAGE_PIN L1 [get_ports {SDRAM_DQSn[1]}]
set_property PACKAGE_PIN M3 [get_ports {SDRAM_DM[1]}]
set_property PACKAGE_PIN M2 [get_ports {SDRAM_DQ[12]}]
set_property PACKAGE_PIN K6 [get_ports {SDRAM_DQ[13]}]
set_property PACKAGE_PIN J6 [get_ports {SDRAM_DQ[14]}]
set_property PACKAGE_PIN L5 [get_ports {SDRAM_DQ[15]}]
set_property PACKAGE_PIN N4 [get_ports {SDRAM_DM[0]}]
set_property PACKAGE_PIN N3 [get_ports {SDRAM_DQ[0]}]
set_property PACKAGE_PIN R1 [get_ports {SDRAM_DQ[1]}]
set_property PACKAGE_PIN P1 [get_ports {SDRAM_DQ[2]}]
set_property PACKAGE_PIN P5 [get_ports {SDRAM_DQS[0]}]
set_property PACKAGE_PIN P4 [get_ports {SDRAM_DQSn[0]}]
set_property PACKAGE_PIN P2 [get_ports {SDRAM_DQ[3]}]
set_property PACKAGE_PIN N2 [get_ports {SDRAM_DQ[4]}]
set_property PACKAGE_PIN M6 [get_ports {SDRAM_DQ[5]}]
set_property PACKAGE_PIN M5 [get_ports {SDRAM_DQ[6]}]
set_property PACKAGE_PIN P6 [get_ports {SDRAM_DQ[7]}]

# Dedicated GTP quad 216 pins; do not apply SelectIO IOSTANDARD properties.
set_property PACKAGE_PIN C7 [get_ports HDMI_CLK_N]
set_property PACKAGE_PIN A6 [get_ports {HDMI_DATA_N[0]}]
set_property PACKAGE_PIN C5 [get_ports {HDMI_DATA_N[1]}]
set_property PACKAGE_PIN A4 [get_ports {HDMI_DATA_N[2]}]
set_property PACKAGE_PIN F6 [get_ports HDMI_REFCLK_P]

set_property PACKAGE_PIN C19 [get_ports {AVID_B[9]}]
set_property PACKAGE_PIN D20 [get_ports {AVID_B[8]}]
set_property PACKAGE_PIN D19 [get_ports {AVID_B[7]}]
set_property PACKAGE_PIN E19 [get_ports {AVID_B[6]}]
set_property PACKAGE_PIN C18 [get_ports {AVID_B[5]}]
set_property PACKAGE_PIN F19 [get_ports {AVID_B[4]}]
set_property PACKAGE_PIN C17 [get_ports {AVID_B[3]}]
set_property PACKAGE_PIN F20 [get_ports {AVID_B[2]}]
set_property PACKAGE_PIN C20 [get_ports {AVID_G[9]}]
set_property PACKAGE_PIN D22 [get_ports {AVID_G[8]}]
set_property PACKAGE_PIN D21 [get_ports {AVID_G[7]}]
set_property PACKAGE_PIN E22 [get_ports {AVID_G[6]}]
set_property PACKAGE_PIN E21 [get_ports {AVID_G[5]}]
set_property PACKAGE_PIN F21 [get_ports {AVID_G[4]}]
set_property PACKAGE_PIN G22 [get_ports {AVID_G[3]}]
set_property PACKAGE_PIN G21 [get_ports {AVID_G[2]}]
set_property PACKAGE_PIN C22 [get_ports AVID_CLK]
set_property PACKAGE_PIN B22 [get_ports {AVID_R[9]}]
set_property PACKAGE_PIN B21 [get_ports {AVID_R[8]}]
set_property PACKAGE_PIN A21 [get_ports {AVID_R[7]}]
set_property PACKAGE_PIN B20 [get_ports {AVID_R[6]}]
set_property PACKAGE_PIN A20 [get_ports {AVID_R[5]}]
set_property PACKAGE_PIN A19 [get_ports {AVID_R[4]}]
set_property PACKAGE_PIN B18 [get_ports {AVID_R[3]}]
set_property PACKAGE_PIN A18 [get_ports {AVID_R[2]}]

set_property PACKAGE_PIN R4 [get_ports ULPI_REFCLK]
set_property PACKAGE_PIN R3 [get_ports ULPI_RESET]
set_property PACKAGE_PIN R2 [get_ports ULPI_STP]
set_property PACKAGE_PIN T1 [get_ports ULPI_DIR]
set_property PACKAGE_PIN U2 [get_ports ULPI_NXT]
set_property PACKAGE_PIN U1 [get_ports {ULPI_DATA[0]}]
set_property PACKAGE_PIN V2 [get_ports {ULPI_DATA[1]}]
set_property PACKAGE_PIN V3 [get_ports {ULPI_DATA[2]}]
set_property PACKAGE_PIN W1 [get_ports {ULPI_DATA[3]}]
set_property PACKAGE_PIN V4 [get_ports ULPI_CLOCK]
set_property PACKAGE_PIN Y1 [get_ports {ULPI_DATA[4]}]
set_property PACKAGE_PIN Y2 [get_ports {ULPI_DATA[5]}]
set_property PACKAGE_PIN AA1 [get_ports {ULPI_DATA[6]}]
set_property PACKAGE_PIN AB1 [get_ports {ULPI_DATA[7]}]

set_property PACKAGE_PIN AB2 [get_ports AUDIO_MCLK]
set_property PACKAGE_PIN AA3 [get_ports AUDIO_BCLK]
set_property PACKAGE_PIN AA4 [get_ports AUDIO_LRCLK]
set_property PACKAGE_PIN AB3 [get_ports AUDIO_SDO]
set_property PACKAGE_PIN Y3 [get_ports AUDIO_SDI]
set_property PACKAGE_PIN Y4 [get_ports CLOCK_C64_REF]
set_property PACKAGE_PIN AB5 [get_ports CLOCK_C64_SYNTH]

set_property PACKAGE_PIN T21 [get_ports {KBJOY_2_JOY[3]}]
set_property PACKAGE_PIN U22 [get_ports {KBJOY_2_JOY[2]}]
set_property PACKAGE_PIN U21 [get_ports {KBJOY_2_JOY[1]}]
set_property PACKAGE_PIN V22 [get_ports {KBJOY_2_JOY[4]}]
set_property PACKAGE_PIN W21 [get_ports {KBJOY_2_JOY[0]}]
set_property PACKAGE_PIN W22 [get_ports {KBJOY_1_JOY[3]}]
set_property PACKAGE_PIN Y21 [get_ports {KBJOY_1_JOY[2]}]
set_property PACKAGE_PIN Y22 [get_ports {KBJOY_1_JOY[1]}]
set_property PACKAGE_PIN AA21 [get_ports {KBJOY_1_JOY[4]}]
set_property PACKAGE_PIN AB22 [get_ports {KBJOY_1_JOY[0]}]

set_property PACKAGE_PIN B17 [get_ports RMII_REFCLK]
set_property PACKAGE_PIN B16 [get_ports {RMII_TX_DATA[1]}]
set_property PACKAGE_PIN A16 [get_ports {RMII_TX_DATA[0]}]
set_property PACKAGE_PIN B15 [get_ports RMII_TX_EN]
set_property PACKAGE_PIN A15 [get_ports RMII_IRQn]
set_property PACKAGE_PIN C14 [get_ports RMII_RX_ER]
set_property PACKAGE_PIN A14 [get_ports RMII_CRS_DV]
set_property PACKAGE_PIN C13 [get_ports {RMII_RX_DATA[0]}]
set_property PACKAGE_PIN A13 [get_ports {RMII_RX_DATA[1]}]
set_property PACKAGE_PIN B13 [get_ports MDIO_CLK]
set_property PACKAGE_PIN D14 [get_ports MDIO_DATA]
set_property PACKAGE_PIN G13 [get_ports ETH_LED_YELn]

set_property PACKAGE_PIN T18 [get_ports {SLOT_ADDR[15]}]
set_property PACKAGE_PIN U17 [get_ports {SLOT_ADDR[14]}]
set_property PACKAGE_PIN U20 [get_ports {SLOT_ADDR[13]}]
set_property PACKAGE_PIN V19 [get_ports {SLOT_ADDR[12]}]
set_property PACKAGE_PIN F13 [get_ports {SLOT_ADDR[11]}]
set_property PACKAGE_PIN F14 [get_ports {SLOT_ADDR[10]}]
set_property PACKAGE_PIN F15 [get_ports {SLOT_ADDR[9]}]
set_property PACKAGE_PIN F16 [get_ports {SLOT_ADDR[8]}]

set_property PACKAGE_PIN W5 [get_ports {SLOT_ADDR[7]}]
set_property PACKAGE_PIN U6 [get_ports {SLOT_ADDR[6]}]
set_property PACKAGE_PIN AA5 [get_ports {SLOT_ADDR[5]}]
set_property PACKAGE_PIN Y6 [get_ports {SLOT_ADDR[4]}]
set_property PACKAGE_PIN AA6 [get_ports {SLOT_ADDR[3]}]
set_property PACKAGE_PIN V7 [get_ports {SLOT_ADDR[2]}]
set_property PACKAGE_PIN AB7 [get_ports {SLOT_ADDR[1]}]
set_property PACKAGE_PIN Y7 [get_ports {SLOT_ADDR[0]}]
set_property PACKAGE_PIN AB6 [get_ports SPEAKER_DATA]

set_property PACKAGE_PIN T3 [get_ports {SLOT_DATA[7]}]
set_property PACKAGE_PIN T4 [get_ports {SLOT_DATA[6]}]
set_property PACKAGE_PIN U3 [get_ports {SLOT_DATA[5]}]
set_property PACKAGE_PIN T5 [get_ports {SLOT_DATA[4]}]
set_property PACKAGE_PIN U5 [get_ports {SLOT_DATA[3]}]
set_property PACKAGE_PIN W2 [get_ports {SLOT_DATA[2]}]
set_property PACKAGE_PIN V5 [get_ports {SLOT_DATA[1]}]
set_property PACKAGE_PIN W4 [get_ports {SLOT_DATA[0]}]
set_property PACKAGE_PIN R6 [get_ports SLOT_DATADIR]
set_property PACKAGE_PIN T6 [get_ports SLOT_DATAOEn]
set_property PACKAGE_PIN D15 [get_ports SLOT_ADDRDIR]
set_property PACKAGE_PIN D16 [get_ports SLOT_ADDROEn]

set_property PACKAGE_PIN W7 [get_ports SLOT_PHI2]
set_property PACKAGE_PIN Y8 [get_ports SLOT_ROMHn]
set_property PACKAGE_PIN AA8 [get_ports SLOT_DOTCLK]
set_property PACKAGE_PIN AB8 [get_ports SLOT_IO1n]
set_property PACKAGE_PIN V8 [get_ports SLOT_IO2n]
set_property PACKAGE_PIN Y9 [get_ports SLOT_BA]
set_property PACKAGE_PIN W9 [get_ports SLOT_ROMLn]

set_property PACKAGE_PIN U18 [get_ports SLOT_IRQn]
set_property PACKAGE_PIN R17 [get_ports SLOT_NMIn]
set_property PACKAGE_PIN W19 [get_ports SLOT_DMAn]
set_property PACKAGE_PIN W17 [get_ports SLOT_EXROMn]
set_property PACKAGE_PIN V18 [get_ports SLOT_RWn]
set_property PACKAGE_PIN V17 [get_ports SLOT_GAMEn]
set_property PACKAGE_PIN P20 [get_ports SLOT_RST_I]
set_property PACKAGE_PIN M18 [get_ports SLOT_RST_O]
set_property PACKAGE_PIN K17 [get_ports SLOT_SID_ADDR]
set_property PACKAGE_PIN M20 [get_ports SLOT_SID1n]
set_property PACKAGE_PIN N20 [get_ports SLOT_SID2n]

set_property PACKAGE_PIN J22 [get_ports CIA_2_PA2]
set_property PACKAGE_PIN J21 [get_ports {CIA_2_PB[7]}]
set_property PACKAGE_PIN K22 [get_ports {CIA_2_PB[6]}]
set_property PACKAGE_PIN K21 [get_ports CIA_2_PC]
set_property PACKAGE_PIN L21 [get_ports {CIA_2_PB[5]}]
set_property PACKAGE_PIN J19 [get_ports CIA_2_SP]
set_property PACKAGE_PIN K19 [get_ports {CIA_2_PB[4]}]
set_property PACKAGE_PIN M17 [get_ports CIA_2_CNT]
set_property PACKAGE_PIN M22 [get_ports {CIA_2_PB[3]}]
set_property PACKAGE_PIN M21 [get_ports CIA_1_SP]
set_property PACKAGE_PIN N22 [get_ports PADDLE_DIS]
set_property PACKAGE_PIN N17 [get_ports {CIA_PWM[0]}]

set_property PACKAGE_PIN P21 [get_ports {CIA_PWM[1]}]
set_property PACKAGE_PIN R21 [get_ports CIA_RSTn]
set_property PACKAGE_PIN P19 [get_ports {CIA_2_PB[0]}]
set_property PACKAGE_PIN R19 [get_ports CIA_2_FLAGn]
set_property PACKAGE_PIN V20 [get_ports {CIA_2_PB[1]}]
set_property PACKAGE_PIN W20 [get_ports CIA_1_CNT]
set_property PACKAGE_PIN AB20 [get_ports {CIA_2_PB[2]}]
set_property PACKAGE_PIN AA20 [get_ports PADDLE_ADJ]
set_property PACKAGE_PIN AB21 [get_ports C2N_SENSE]
set_property PACKAGE_PIN Y18 [get_ports C2N_READ]
set_property PACKAGE_PIN Y19 [get_ports C2N_WRITE]
set_property PACKAGE_PIN H13 [get_ports CIA_BUFFER_EN]

set_property PACKAGE_PIN R14 [get_ports LED_CLOCK]
set_property PACKAGE_PIN M15 [get_ports LED_DATA]
set_property PACKAGE_PIN H19 [get_ports LED_CASE1n]
set_property PACKAGE_PIN H17 [get_ports LED_CASE2n]
set_property PACKAGE_PIN G17 [get_ports LED_CASE3n]

set_property PACKAGE_PIN L13 [get_ports WIFI_BOOT]
set_property PACKAGE_PIN L14 [get_ports WIFI_CTS]
set_property PACKAGE_PIN M13 [get_ports WIFI_DIS]
set_property PACKAGE_PIN N13 [get_ports WIFI_RXD]
set_property PACKAGE_PIN N14 [get_ports WIFI_RTS]
set_property PACKAGE_PIN P14 [get_ports WIFI_TXD]

set_property PACKAGE_PIN N15 [get_ports UART_TXD]
set_property PACKAGE_PIN P15 [get_ports UART_RXD]
set_property PACKAGE_PIN J16 [get_ports BLING_KEYB]
set_property PACKAGE_PIN R16 [get_ports BLING_LED]

set_property PACKAGE_PIN H18 [get_ports HDMI_HPD]
set_property PACKAGE_PIN K18 [get_ports HDMI_SDA]
set_property PACKAGE_PIN L20 [get_ports HDMI_SCL]
set_property PACKAGE_PIN D17 [get_ports HDMI_CLK_SYNTH]
set_property PACKAGE_PIN N19 [get_ports HDMI_DDC_EN]

set_property PACKAGE_PIN C15 [get_ports {BOARD_REVn[0]}]
set_property PACKAGE_PIN E13 [get_ports {BOARD_REVn[1]}]
set_property PACKAGE_PIN E17 [get_ports {BOARD_REVn[2]}]

set_property PACKAGE_PIN P17 [get_ports {UI_BUTTON[0]}]
set_property PACKAGE_PIN R18 [get_ports {UI_BUTTON[1]}]
set_property PACKAGE_PIN N18 [get_ports {UI_BUTTON[2]}]

set_property PACKAGE_PIN W6 [get_ports I2C18_SDA]
set_property PACKAGE_PIN U7 [get_ports I2C18_SCL]

set_property PACKAGE_PIN K13 [get_ports IEC_RESET_I]
set_property PACKAGE_PIN K14 [get_ports IEC_SRQ_I]
set_property PACKAGE_PIN J14 [get_ports IEC_ATN_I]
set_property PACKAGE_PIN J15 [get_ports IEC_DATA_I]
set_property PACKAGE_PIN G15 [get_ports IEC_CLOCK_I]
set_property PACKAGE_PIN H14 [get_ports IEC_RESET_O]
set_property PACKAGE_PIN J17 [get_ports IEC_SRQ_O]
set_property PACKAGE_PIN G16 [get_ports IEC_ATN_O]
set_property PACKAGE_PIN L18 [get_ports IEC_DATA_O]
set_property PACKAGE_PIN L19 [get_ports IEC_CLOCK_O]

set_property PACKAGE_PIN E14 [get_ports {PADDLE_CMP[0]}]
set_property PACKAGE_PIN P16 [get_ports LED_BOARDn]
set_property PACKAGE_PIN L6 [get_ports {PADDLE_CMP[1]}]
set_property PACKAGE_PIN N5 [get_ports {PADDLE_CMP[2]}]
set_property PACKAGE_PIN L4 [get_ports {PADDLE_CMP[3]}]

set_property PACKAGE_PIN AA18 [get_ports SD_SSn]
set_property PACKAGE_PIN AB18 [get_ports SD_CLK]
set_property PACKAGE_PIN AA19 [get_ports SD_MOSI]
set_property PACKAGE_PIN T20 [get_ports SD_MISO]

set_property PACKAGE_PIN H22 [get_ports AUDIO_SPDIF]
set_property PACKAGE_PIN H20 [get_ports C2N_MOTOR]
set_property PACKAGE_PIN J20 [get_ports HUB_RESETn]
set_property PACKAGE_PIN E18 [get_ports AVID_FB]
set_property PACKAGE_PIN F18 [get_ports AVID_SYNCn]
set_property PACKAGE_PIN V9 [get_ports KBJOY_INT]
set_property PACKAGE_PIN M16 [get_ports KBJOY_RESTORE]
set_property PACKAGE_PIN G18 [get_ports CIA_PWR_EN]
set_property PACKAGE_PIN G20 [get_ports HUB_CLOCK]
set_property PACKAGE_PIN H15 [get_ports I2C33_SDA]
set_property PACKAGE_PIN L15 [get_ports SLOT_PWR]
set_property PACKAGE_PIN L16 [get_ports SD_CARDDETn]
set_property PACKAGE_PIN K16 [get_ports I2C33_SCL]

set_property PACKAGE_PIN P22 [get_ports FLASH_MOSI]
set_property PACKAGE_PIN R22 [get_ports FLASH_MISO]
#set_property PACKAGE_PIN V22 [get_ports FLASH_SCK]
set_property PACKAGE_PIN T19 [get_ports FLASH_CSn]

set_property PULLTYPE PULLUP [get_ports BLING_KEYB]
set_property PULLTYPE PULLUP [get_ports UART_RXD]
set_property PULLTYPE PULLUP [get_ports CIA_RSTn]

set_property PULLTYPE PULLUP [get_ports {KBJOY_1_JOY[4]}]
set_property PULLTYPE PULLUP [get_ports {KBJOY_1_JOY[3]}]
set_property PULLTYPE PULLUP [get_ports {KBJOY_1_JOY[2]}]
set_property PULLTYPE PULLUP [get_ports {KBJOY_1_JOY[1]}]
set_property PULLTYPE PULLUP [get_ports {KBJOY_1_JOY[0]}]
set_property PULLTYPE PULLUP [get_ports {KBJOY_2_JOY[4]}]
set_property PULLTYPE PULLUP [get_ports {KBJOY_2_JOY[3]}]
set_property PULLTYPE PULLUP [get_ports {KBJOY_2_JOY[2]}]
set_property PULLTYPE PULLUP [get_ports {KBJOY_2_JOY[1]}]
set_property PULLTYPE PULLUP [get_ports {KBJOY_2_JOY[0]}]

set_property PULLTYPE PULLUP [get_ports {UI_BUTTON[0]}]
set_property PULLTYPE PULLUP [get_ports {UI_BUTTON[1]}]
set_property PULLTYPE PULLUP [get_ports {UI_BUTTON[2]}]

set_property PULLTYPE PULLUP [get_ports C2N_READ]
set_property PULLTYPE PULLUP [get_ports C2N_WRITE]


set_property PACKAGE_PIN B6 [get_ports HDMI_CLK_P]
set_property PACKAGE_PIN B5 [get_ports {HDMI_DATA_P[0]}]
set_property PACKAGE_PIN B4 [get_ports {HDMI_DATA_P[1]}]
set_property PACKAGE_PIN B3 [get_ports {HDMI_DATA_P[2]}]
set_property PACKAGE_PIN E6 [get_ports HDMI_REFCLK_N]
